# Generated by Django 4.2.13 on 2024-08-20 18:04

from django.db import migrations, models
import django_celery_beat.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django_celery_beat.utils.now, verbose_name='Время последнего посещения'),
        ),
    ]
