# Generated by Django 4.2.13 on 2024-08-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_lesson_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('can_view_course', 'Может просматривать курсы'), ('can_edit_course', 'Может редактировать курсы')], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'permissions': [('can_view_lesson', 'Может просматривать уроки'), ('can_edit_lesson', 'Может редактировать уроки')], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
