# Generated by Django 4.2.13 on 2024-08-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, help_text='Укажите ссылку', max_length=300, null=True, verbose_name='ссылка на видео'),
        ),
    ]
