# Generated by Django 4.2.13 on 2024-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
